#:schema node_modules/wrangler/config-schema.json
name = "oo-remix-drizzle"
compatibility_date = "2024-06-14"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "drizzle-todo"
database_id = "8314dc0a-da28-4737-a893-62d742bf3ade"
migrations_dir = "./drizzle/migrations"